---
title: 10,000 Reasons
youtube: DXDGE_lRI0E
categories:
 - Engelske sanger
title-block-banner: false
author:
 - name: Matt Redman
   roles: "Text and lyrics"
 - name: Jonas Myrin
   roles: "Text and lyrics"
---

> ‘Praise the Lord, my soul; all my inmost being, praise his holy name. Praise the Lord, my soul, and forget not all his benefits – who forgives all your sins and heals all your diseases, who redeems your life from the pit and crowns you with love and compassion, who satisfies your desires with good things so that your youth is renewed like the eagle’s.‘ (NIV)

> Psalm 103.1 - 5

[Chorus]  
Bless the Lord, O my soul  
O my soul  
Worship His holy name  
Sing like never before  
O my soul  
I'll worship Your holy name

[Verse 1]  
The sun comes up, it's a new day dawning  
It's time to sing Your song again  
Whatever may pass,  
and whatever lies before me  
Let me be singing when the evening comes

[Chorus]  
Bless the Lord, O my soul  
O my soul  
Worship His holy name  
Sing like never before  
O my soul  
I'll worship Your holy name

[Verse 2]  
You're rich in love, and You're slow to anger  
Your name is great, and Your heart is kind  
For all Your goodness I will keep on singing  
Ten thousand reasons for my heart to find

[Chorus]  
Bless the Lord, O my soul  
O my soul  
Worship His holy name  
Sing like never before  
O my soul  
I'll worship Your holy name 

[Verse 3]  
And on that day when my strength is failing  
The end draws near and my time has come  
Still my soul will sing Your praise unending  
Ten thousand years and then forevermore

[Chorus]  
Bless the Lord, O my soul  
O my soul  
Worship His holy name  
Sing like never before  
O my soul  
I'll worship Your holy name  
(x2)

[Outro]  
I'll worship Your holy name  
Lord, I'll worship Your holy name

Sing like never before  
O my soul  
I'll worship Your holy name  
I'll worship Your holy name  
I'll worship Your holy name