---
title: Anchor for the soul
categories: "Engelske sanger"
youtube: QRg1WckNox4
spotify: 6xXIg2eSJa5iepylw9NUq7
quote: "Dette har vi som et anker for sjelen, et som er trygt og fast og når inn til det innerste, bak forhenget, der Jesus gikk inn som forløper for oss, han som ble yppersteprest til evig tid etter Melkisedeks vis. Hebreerne 6.19 - 20"
---

**Chorus**  
Anchor for the soul  
Shelter from the storm  
Thunder and the lightning  
Can be very fright'ning  
But God is in control  
Anchor for the soul  
Shelter from the storm  
Manna in the morning  
Blessings overflowing  
Leading us to home

This world's not my home  
Just a-passing through  
Through this life I wander  
Treasure stored up yonder  
Somewhere beyond the blue  
On my way I learn  
Through each path I take  
Every day I'm growing  
On my way I'm knowing  
Heaven's worth the wait

**Chorus**  
Anchor for the soul  
Shelter from the storm  
Thunder and the lightning  
Can be very fright'ning  
But God is in control  
Anchor for the soul  
Shelter from the storm  
Manna in the morning  
Blessings overflowing  
Leading us to home

When the day is gone  
When my journey ends  
Won't be nothing better  
Then to be together  
With all my faithful friends  
We'll all join in song  
Gathered 'round the throne  
There'll be no more sorrow  
Someday when tomorrow  
Heaven is our home

**Chorus**  
Anchor for the soul  
Shelter from the storm  
Thunder and the lightning  
Can be very fright'ning  
But God is in control  
Anchor for the soul  
Shelter from the storm  
Manna in the morning  
Blessings overflowing  
Leading us to home
