---
title: Awesome
categories: "Engelske sanger"
youtube: -DNRJIZIZm4
---

My God is awesome  
He can move mountains  
Keep me in the valley  
Hide me from the rain

My God is awesome  
He heals me when I'm broken  
Gives strength where I've been weakened  
Forever He will reign

My God is awesome  
He can move mountains  
Keep me in the valley  
Hide me from the rain

My God is awesome  
He heals me when I'm broken  
Strength where I've been weakened  
Forever He will reign

My God is awesome, awesome, awesome, awesome  
My God is awesome, awesome, awesome, awesome

My God is awesome  
Savior of the whole world  
Giver of salvation  
By His stripes I am healed

My God is awesome  
Today I am forgiven  
His grace is why I'm living  
(Somebody ought to) Praise His holy name

My God is awesome, awesome, awesome, awesome  
My God is awesome, awesome, awesome, awesome

He's mighty  
He's mighty  
He's mighty  
He's mighty  
Awesome, awesome

He's holy  
He's holy  
He's holy  
He's holy  
Awesome, awesome

He's great  
He's great  
He's great  
He's great  
Awesome, awesome

He's mighty  
He's mighty  
He's mighty  
He's mighty  
Awesome, awesome

Deliverer  
Deliverer  
Deliverer  
Deliverer  
Awesome, awesome

He's holy  
He's holy  
He's holy  
He's holy  
Awesome, awesome

Provider  
Provider  
Provider  
Provider  
Awesome, awesome

Protector  
Protector  
Protector  
Protector  
Awesome, awesome

My God is awesome  
He can move mountains  
Keep me in the valley  
Hide me from the rain

My God is awesome  
Heals me when I'm broken  
Gives strength where I've been weakened  
Praise His holy name
