---
title: Be With Me Lord
categories: "Engelske sanger"
youtube: JrklsK0OWPI
---

Sometimes I feel  
That I could fight an army  
With just me and you,  
And there's no one could harm me.  
O, but sometimes I  
Can feel a little shy.  
It's then I need to know  
That you are there, that's why I'm singing

**Chorus:**  
Be with me Lord (when I'm down)  
Be with me Lord (when I'm lonely)  
Be with me Lord (when I'm tired)  
be with me, be with me   
Be with me Lord (I need you only)  
Be with me Lord (when I'm down)  
Be with me Lord (when I'm lonely)  
Be with me Lord (when I need you, Lord)  
Be my only God.

I know you said  
That I would not be tested  
More than I could bear  
And that you'd have my best in mind.  
With everything  
That ever comes my way,  
I know you're in control  
So hear me as I pray. I'm singing.

**Chorus:**  
Be with me Lord (when I'm down)  
Be with me Lord (when I'm lonely)  
Be with me Lord (when I'm tired)  
be with me, be with me, be with me  
Be with me Lord (I need you only)  
Be with me Lord (when I'm down)  
Be with me Lord (when I'm lonely)  
Be with me Lord (when I need you, Lord)  
Be my only God.

Now help me, Lord  
To share what I've been given.  
Help me make a difference  
With this life I'm living.  
As I show my neighbor  
Where true treasure's stored,  
Help me know you promised  
You'd be with me Lord. I'm singing.

**Chorus:**  
Be with me Lord (when I'm down)  
Be with me Lord (when I'm lonely)  
Be with me Lord (when I'm tired)  
Be with me Lord (I need you only)  
Be with me Lord (when I'm down)  
Be with me Lord (when I'm lonely)  
Be with me Lord (when I need you, Lord)  
Be my only God.