---
title: Don't you want to go to that land
categories: "Engelske sanger"
youtube: 5lypJdhVtBI
---

Don't you wanna go to that land;  
Don't you wanna go to that land  
Where I'm bound, where I'm bound?  
Don't you wanna go to that land,  
Don't you wanna go to that land;  
Don't you wanna go to that land  
Where I'm bound, where I'm bound?

Nothin' but love in that land,  
Nothin' but love in that land;  
Nothin' but love in that land  
Where I'm bound, where I'm bound.  
Nothin' but love in that land,  
Nothin' but love in that land;  
Nothin' but love in that land  
Where I'm bound, where I'm bound.

Nothin' but joy in that land,  
Nothin' but joy in that land;  
Nothin' but joy in that land  
Where I'm bound, where I'm bound.  
Nothin' but joy in that land,  
Nothin' but joy in that land;  
Nothin' but joy in that land  
Where I'm bound, where I'm bound.

Nothin' but peace in that land,  
Nothin' but peace in that land;  
Nothin' but peace in that land  
Where I'm bound, where I'm bound.  
Nothin' but peace in that land,  
Nothin' but peace in that land;  
Nothin' but peace in that land  
Where I'm bound, where I'm bound.

I've got a Savior in that land,  
I've got a Savior in that land;  
I've got a Savior in that land  
Where I'm bound, where I'm bound.  
I've got a Savior in that land,  
I've got a Savior in that land;  
I've got a Savior in that land  
Where I'm bound, where I'm bound.