---
title: Forever
categories: "Engelske sanger"
youtube: d6xxWGWpaUQ
---

His love endures forever...

Give thanks to the Lord our God and King  
His love endures forever.  
For He is good, He's above all things  
His love endures forever.

Sing praise, Sing praise,  


With mighty hand and outstretched arm  
His love endures forever.  
For the life that's been reborn  
His love endures forever.

**Chorus:** 
Sing praise, Sing praise,  
Sing praise, Sing praise,  
Forever God is faithful,  
Forever God is strong,  
Forever God is with us,
Forever

From the rising to the setting sun  
His love endures forever.  
And by the grace of God we will carry on  
His love endures forever.

**Chorus:** 
Sing praise, Sing praise,  
Sing praise, Sing praise,  
Forever God is faithful,  
Forever God is strong,  
Forever God is with us,
Forever

(mellomspill)  

Sing praise, Sing praise,  
Sing praise, Sing praise,  
Sing praise, sing praise
Sing prise, sing praise

Forever God is faithful,  
Forever God is strong,  
Forever God is with us,
Forever

Forever you are faithful  
Forever you are strong  
Forever you are with us  
Forever and ever