---
title: "Good good father"
categories: "Engelske sanger"
youtube: -ak0OoFBw3c
spotify: 1mWdyqs6Zvg8b1lKjDc8yB
---

Oh, I've heard a thousand stories of what they think you're like  
But I've heard the tender whisper of love in the dead of night  
And you tell me that you're pleased  
And that I'm never alone

You're a Good, Good Father  
It's who you are, it's who you are, it's who you are  
And I'm loved by you  
It's who I am, it's who I am, it's who I am

Oh, and I've seen many searching for answers far and wide  
But I know we're all searching  
For answers only you provide  
'Cause you know just what we need  
Before we say a word

You're a Good, Good Father  
It's who you are, it's who you are, it's who you are  
And I'm loved by you  
It's who I am, it's who I am, it's who I am

'Cause you are perfect in all of your ways  
You are perfect in all of your ways  
You are perfect in all of your ways to us

You are perfect in all of your ways  
You are perfect in all of your ways  
You are perfect in all of your ways to us

Oh, it's love so undeniable  
I, I can hardly speak  
Peace so unexplainable  
I, I can hardly think

As you call me deeper still  
As you call me deeper still  
As you call me deeper still  
Into love, love, love

You're a Good, Good Father  
It's who you are, it's who you are, it's who you are  
And I'm loved by you  
It's who I am, it's who I am, it's who I am

You're a Good, Good Father  
It's who you are, it's who you are, it's who you are  
And I'm loved by you  
It's who I am, it's who I am, it's who I am

You're a Good, Good Father  
It's who you are, it's who you are, it's who you are  
And I'm loved by you  
It's who I am, it's who I am, it's who I am

You're a Good, Good Father  
(You are perfect in all of your ways)  
It's who you are, it's who you are, it's who you are  
And I'm loved by you  
(You are perfect in all of your ways)  
It's who I am, it's who I am it's who I am
