---
title: "Heart, Mind And Soul"
categories: "Engelske sanger"
---

One heart, mind and soul,  
we will always stand together  
One heart, mind and soul,  
and our unity will show that  
One heart, mind and soul,  
we will always stand together  
One heart, mind and soul,  
and our unity will show that  
He is Lord

One heart, to be united,  
One heart, in everything  
One heart, to stay enlighted,  
One heart, and away from sin  
One heart, that is forgiven,  
One heart, and knows the truth  
One heart, where the spirit ´s living  
One heart, with a strenght of youth

One heart, mind and soul,  
we will always stand together  
One heart, mind and soul,  
and our unity will show that  
One heart, mind and soul,  
we will always stand together  
One heart, mind and soul,  
and our unity will show that  
He is Lord

One mind, made up for Jesus  
One mind, we won ´t be fooled  
One mind, His word will lead us  
One mind, yes, the Bible rules  
One mind, who shares the same dream  
One mind, that Jesus lived  
One mind, to obey his saying  
One mind, and do the things he did

One heart, mind and soul,  
we will always stand together  
One heart, mind and soul,  
and our unity will show that  
One heart, mind and soul,  
we will always stand together  
One heart, mind and soul,  
and our unity will show that  
He is Lord

One soul, we come to you Lord  
One soul, when down and low  
One soul, we pray for power  
One soul, to be restored  
One soul, we love each other  
One soul, to keep us strong  
One soul, my sister and brother  
One soul, in heaven we belong

One heart, mind and soul,  
we will always stand together  
One heart, mind and soul,  
and our unity will show that  
One heart, mind and soul,  
we will always stand together  
One heart, mind and soul,  
and our unity will show that  
He is Lord
