---
title: "Here I am to worship"
categories: "Engelske sanger"
youtube: FaUTv1pXRyU
---

Light of the world,  
You step down into darkness  
Open my eyes let me see  
Beauty that made this heart adore you  
Hope of a life spent with you

Here I am to worship  
Here I am to bow down  
Here I am to say that you're my God  
You're altogether lovely  
Altogether worthy  
Altogether wonderful to me, my love

King of all days  
So highly exalted  
Glorious in heaven above  
Humbly you came to the earth you created  
All for love's sake became poor

So, here I am to worship  
Here I am to bow down  
Here I am to say that you're my God  
You're altogether lovely  
Altogether worthy  
Altogether wonderful to me

I'll never know how much it cost  
To see my sin upon that cross  
And I'll never know how much it cost  
To see my sin upon that cross

I'll never know how much it cost  
To see my sin upon that cross  
I'll never know how much it cost  
To see my sin upon that cross

Here I am to worship  
Here I am to bow down  
Here I am to say that you're my God  
You're altogether lovely  
Altogether worthy  
Altogether wonderful to me

So, here I am to worship  
Here I am to bow down  
Here I am to say that you're my God  
You're altogether lovely  
Altogether worthy  
Altogether wonderful to me 
