---
title: "High Above"
categories: "Engelske sanger"
---

Before a word was on my lips  
You knew my mind's full intention  
Before a thought came to my mind  
You could read it completely, from afar

I took the wings of the red morning sun  
But you found me, at the end of the ocean  
I tried to hide in the darkest night  
But darkness turned to light, you shone all around me

**Chorus**  
High above the clouds  
Were skies are blue  
My soul, my mind, my spirit will be home  
High above the clouds  
I´ll be with you  
My soul, my mind, my spirit will be home  
With you, always...

When I was high, when I was low  
You were there, you could reach me  
When I was made, in the secret place  
I was hidden from all, but from your eyes  
All the days you ordained for me  
Were set down, long before, they came to be  
Search my ways Lord, and guard my heart  
Lead me in your way, the way everlasting

What can I do, what can I say  
it´s too wonderful to me  
You brought me in, you knew my ways  
Laid your hand all upon me, made me safe  
All the days you ordained for me  
Where set down long before, they came to be  
Search my ways Lord and guard my heart  
Lead me in your way, the way everlasting
