---
title: I Hear God Singing To Me
categories: Engelske sanger
youtube: NdyfhctYxs0
---

**Intro:**  
(Solo): Well, I hear God singing to me.  
(All): Every nation must be saved.  
(Solo): Well, I hear God singing to me.  
(All): Every Challenge must be braved.  
(Solo): Oh, I feel God's spirit in me.  
(All): Quench it not too much at stake.  
(Solo): Well, I hear God singing to me.  
(All): II: I hear God sing for Jesus sake. :II 

**Chorus:**  
II: I hear God singing to me :II

I hear God singing and rejoicing  
and I love my Father's song  
I hear God singing and He's saying  
everyone should sing along  
Righteous singing scares the devil,  
so let's shout our anthems loud!  
A soldier's choir in holy concert;  
voices lifted, faces bowed.

**Chorus:**  
II: I hear God singing to me :II

Gather us and start a movement,  
scatter us, we scatter seeds;  
Planting Christ in every nation,  
as our great crusade succeeds.  
Criticize us we grow stronger,  
kill us and for sure we win;  
for our battle isn't earthly  
and our souls will never end.

**Chorus:**  
II: I hear God singing to me :II

**Bridge:**  
(Men):  
Suhkeeuh Moongoo ahkeeyeembah :/

(Women):  
Hear God sing for Jesus sake :/

**Chorus:**  
II: I hear God singing to me :II
