---
title: "I need your love"
categories: "Engelske sanger"
youtube: gLjXYzIhf4I
---

O I need your love  
In this shadowed place  
I can't get enough  
Of your sunlight on my face.

When it's cold and dark  
Or I'm far from home  
You are in my heart  
And I never walk alone.

And just like a tree  
Planted by a stream,  
Thirsty for a drink  
Of your love,  
I can't face a day  
Without some time to pray  
I sing this song to say  
I need your love.

I'm a tiny child  
But when I'm with you  
I will not grow tired  
'Cause there's nothing you can't do.  
Your love makes me strong  
Though I'm small and weak,  
And the whole day long  
You'll speak through me when I speak.

And just like a tree  
Planted by a stream,  
Thirsty for a drink  
Of your love,  
I can't face a day  
Without some time to pray  
I sing this song to say  
I need your love.

You gave all for me  
Though I cursed your name  
On that bitter tree,  
Lord, You suffered for my shame.  
How can I thank you?  
Your love paid my way.  
All that I can do  
Is live for You every day.

And just like a tree  
Planted by a stream,  
Thirsty for a drink  
Of your love,  
I can't face a day  
Without some time to pray  
I sing this song to say  
I need your love.
