---
title: I want to know your peace
categories: "Engelske sanger"
---

Thinking of all the mistakes I've been making,  
promises I have been breaking,  
humility I have been faking,  
God, I need some help  
Hoping that I can let go of delaying,  
bow down my head and start praying,  
listen to what you are saying,  
God, I need some help

Lord, please listen to my cry  
I don't know how to get by  
Can't you see I'm on my knees?  
I want to know your peace  
Make me stronger, make me new  
Nothing changes without you  
Put my troubled soul at ease  
I want to know your peace

Choosing to think that my friends are accusing,  
I live in fear, I am losing.  
Things are a little confusing,  
God, I need some help  
Can you help me to be like the man you  
sent to help us understand you?  
Give me a heart that is brand new  
God, I need some help

Lord, please listen to my cry  
I don't know how to get by  
Can't you see I'm on my knees?  
I want to know your peace  
Make me stronger, make me new  
Nothing changes without you  
Put my troubled soul at ease  
I want to know your peace

Father, I am down, I'm a fool, I'm a clown  
I can feel Satan's breath in my face  
When I am sad, when I'm broken and bad,  
what I need is to rest in your grace

Lord, please listen to my cry  
I don't know how to get by  
Can't you see I'm on my knees?  
I want to know your peace  
Make me stronger, make me new  
Nothing changes without you  
Put my troubled soul at ease  
I want to know your peace
