---
title: In the Kingdom
categories: "Engelske sanger"
---

1F: Are you standing in the place that will stand forever?  
A: Standing, singing, yes, I am.  
F: Are you standing in the place that can stand the weather  
A: Standing, singing, yes, I am.

**Choir:**  
In the Kingdom, one by one, in the Kingdom, hand in hand  
In the Kingdom, for his Son, in the Kingdom, we will stand  
In the Kingdom, side by side, in the Kingdom, one and all  
In the Kingdom, we'll not hide, in the Kingdom, we'll not fall

F: Are you walking the road that will lead to heaven?  
A: Walking, singing, yes, I am.  
F: Are you reading the word that will read forever?  
A: Reading, singing, yes, I am.

**Choir:**  
In the Kingdom, one by one, in the Kingdom, hand in hand  
In the Kingdom, for his Son, in the Kingdom, we will stand  
In the Kingdom, side by side, in the Kingdom, one and all  
In the Kingdom, we'll not hide, in the Kingdom, we'll not fall

F: Are you sharing the word that you can share forever?  
A: Sharing, singing, yes, I am.  
F: Are you sharing your life that you can share forever?  
A: Sharing, singing, yes, I am.

**Choir:**  
In the Kingdom, one by one, in the Kingdom, hand in hand  
In the Kingdom, for his Son, in the Kingdom, we will stand  
In the Kingdom, side by side, in the Kingdom, one and all  
In the Kingdom, we'll not hide, in the Kingdom, we'll not fall








