---
title: In the river
categories: "Engelske sanger"
youtube: 7jE-ODROpyY
---

There is a river where goodness flows  
There is a fountain that drowns sorrow  
There is an ocean deeper than fear  
The tide is rising, rising

There is a current stirring deep inside  
It's overflowing from the heart of God  
The flood of heaven crashing over us  
The tide is rising, rising

Bursting, bursting  
Up from the ground  
We feel it now  
Bursting, bursting  
Up from the ground  
We feel it now

We come alive in the river  
We come alive in the river  
We come alive in the river  
We come alive in the river  

There is a current stirring deep inside  
It's overflowing from the heart of God  
The flood of heaven crashing over us  
The tide is rising, rising

Bursting, bursting  
Up from the ground  
We feel it now  
Bursting, bursting  
Up from the ground  
We feel it now

We come alive in the river  
We come alive in the river  
We come alive in the river  
We come alive in the river

Break open prison doors  
Set all the captives free  
Spring up a well, spring up a well  
Spring up a well in me

Nothing can stop this joy  
We're dancing in the street  
Spring up a well, spring up a well  
Spring up a well in me

We come alive in the river  
We come alive in the river  
We come alive in the river  
We come alive in the river

Bursting, bursting  
Up from the ground  
We feel it now  
Bursting, bursting  
Up from the ground  
We feel it now

We come alive in the river  
We come alive in the river  
We come alive in the river  
We come alive in the river

Spring up a well  
Spring up a well  
Spring up a well in me  
Spring up a well  
Spring up a well  
Spring up a well in me
