---
title: "It is well"
categories: "Engelske sanger"
youtube: YNqo4Un2uZI
---

Grander earth has quaked before  
Moved by the sound of His voice  
Seas that are shaken and stirred  
Can be calmed and broken for my regard

**Chorus**  
Through it all, through it all  
My eyes are on You  
Through it all, through it all  
It is well  
Through it all, through it all  
My eyes are on You  
It is well with me

Far be it from me to not believe  
Even when my eyes can't see  
And this mountain that's in front of me  
Will be thrown into the midst of the sea

**Chorus**  
Through it all, through it all  
My eyes are on You  
Through it all, through it all  
It is well  
Through it all, through it all  
My eyes are on You  
It is well, it is well

So let go my soul and trust in Him  
The waves and wind still know His name  
So let go my soul and trust in Him  
The waves and wind still know His name  
So let go my soul and trust in Him  
The waves and wind still know His name  
The waves and wind still know His name

It is well with my soul  
It is well with my soul  
It is well with my soul  
It is well, it is well, with my soul  
It is well with my soul  
It is well with my soul  
It is well with my soul  
It is well, it is well, with my soul  
It is well, it is well, with my soul  
It is well, it is well, with my soul

**Chorus**  
Through it all, through it all  
My eyes are on You  
Through it all, through it all  
It is well  
Through it all, through it all  
My eyes are on You  
And it is well with me 
