---
title: Lead Me To The Rock
categories: "Engelske sanger"
youtube: tN65VE7H4-U
---

**Chorus**
Lead me to the rock that is  
higher than I,  
higher than I, higher than I.  
Lead me to the rock that is higher than I,  
You're my tower against the foe.

Hear my cry O God, answer my prayer,  
answer my prayer, answer my prayer,  
Hear my cry O God, answer my prayer,  
You're my tower against the foe.

**Chorus**
Lead me to the rock that is  
higher than I,  
higher than I, higher than I.  
Lead me to the rock that is higher than I,  
You're my tower against the foe.

I'll take refuge in the shelter of your wings,  
the shelter of your wings, the shelter of your wings,  
I'll take refuge in the shelter of your wings,  
You're my tower against the foe.

**Chorus**
Lead me to the rock that is  
higher than I,  
higher than I, higher than I.  
Lead me to the rock that is higher than I,  
You're my tower against the foe.

I fulfill my vows, day after day, day after day,  
day after day I'll fulfill my vows, day after day,  
You're my tower against the foe.

**Chorus**
Lead me to the rock that is  
higher than I,  
higher than I, higher than I.  
Lead me to the rock that is higher than I,  
You're my tower against the foe.
