---
title: Lead me to Calvary
categories: "Engelske sanger"
youtube: iezvIqW98VA
---

King of my life, I crown Thee now. Thine shall the glory be  
Lest I forgot Thy thorncrown, lead me to Calvary

**Choir:**  
  |  |: Lest I forget Getshemane, Lest I forget Thine agony  
Lest I forget Thy love for me, lead me to Calvary :  |  |

Show me the tomb where Thou was laid. Tenderly mourned and wept  
Angels in robes of light arrayed guarded Theee whilst Thou
slept

**Choir:**  
  |  |: Lest I forget Getshemane, Lest I forget Thine agony  
Lest I forget Thy love for me, lead me to Calvary :  |  |

Let me like Mary, through the gloom, come with a gift to Thee  
Show to me now the empty tomb, lead me to Calvary

**Choir:**  
  |  |: Lest I forget Getshemane, Lest I forget Thine agony  
Lest I forget Thy love for me, lead me to Calvary :  |  |

May I be willing, Lord, to bear daily my cross for Thee  
Even Thy cup of grief to share. Thou hast borne all for me

**Choir:**  
  |  |: Lest I forget Getshemane, Lest I forget Thine agony  
Lest I forget Thy love for me, lead me to Calvary :  |  |
