---
title: Let it rise
categories: "Engelske sanger"
youtube: KwqI2b8TpqY 
---

Let the Spirit of the Lord, rise among us  
Let the Spirit of the Lord, rise among us  
Let the spirit of our King rise among us  
Let it rise (twice)

Oh - oh - oh, let it rise  
Oh - oh - oh, let it rise

Let the glory of the Lord, rise among us  
Let the glory of the Lord, rise among us  
Let the praises of the King rise among us  
Let it rise (twice)

Oh - oh - oh, let it rise  
Oh - oh - oh, let it rise

Let the songs of the Lord, rise among us  
Let the songs of the Lord, rise among us  
Let the joy of our King, rise among us  
Let it rise (twice)

Oh - oh - oh, let it rise  
Oh - oh - oh, let it rise

Let the Spirit of the Lord, rise among us 
Let the Spirit of the Lord, rise among us 
Let the praises of the King rise among us 
Let it rise (twice)

Oh - oh - oh, let it rise  
Oh - oh - oh, let it rise

Let the freedom of the Lord, rise among us  
Let the freedom of the Lord, rise among us  
Let the mercy of the Lord, rise among us  
Let it rise (twice)

Oh - oh - oh, let it rise  
Oh - oh - oh, let it rise

Let the joy of the king, rise among us  
Let the joy of the king, rise among us  
Let the praises of the Lord, rise among us  
Let it rise (twice)

Oh - oh - oh, let it rise  
Oh - oh - oh, let it rise