---
title: Men who dream
categories: "Engelske sanger"
---

Captives came back into Zion  
From their freedom came a scheme  
While the city, it lay in ruins  
We believe they had a dream...

When our souls were like the desert  
And we stumbled on the stream  
And found revival in the water  
We became like men who dream

And yes our mouths  
were filled with laughter  
And our songs rushed like the stream  
Where he washed our sorrows under  
We became like men who dream

It shall be said among the nations,  
"There's a God who shares our dream."  
The Spirit moves our generation  
Shed your tears, fill the stream

Men who dream  
We are shedding tears that  
Flood the thirsty waters  
Men who dream  
We are planting seeds of  
Men who dream

God has done great things among us  
Every eye now shines a gleam  
A spark of light reveals the wonder  
We became like men who dream...

So let us go into the nations  
Plunging souls into that stream  
And singing songs that stir the angels  
We became the men who dream.
