---
title: Mighty to save
categories: Engelske sanger
youtube: AW2LEU5v8VA
---

Everyone needs compassion  
A love that's never failing  
Let mercy fall on me

Everyone needs forgiveness  
The kindness of a Saviour  
The hope of nations

**Chorus**  
Saviour, he can move the mountains  
My God is mighty to save  
He is mighty to save  
Forever Author of Salvation  
He rose and conquered the grave  
Jesus conquered the grave

So take me as you find me  
All my fears and failures  
Fill my life again

I give my life to follow  
Everything that I believe in  
Now I surrender

**Chorus**  
Saviour, he can move the mountains  
My God is mighty to save  
He is mighty to save  
Forever Author of Salvation  
He rose and conquered the grave  
Jesus conquered the grave

Shine your light and let the whole world see  
We're singing for the glory of the risen king (2x)

**Chorus**  
Saviour, he can move the mountains  
My God is mighty to save  
He is mighty to save  
Forever Author of Salvation  
He rose and conquered the grave  
Jesus conquered the grave
(2x)

Shine your light and let the whole world see  
We're singing for the glory of the risen king Jesus (6x)


