---
title: Nobody knows
categories: Engelske sanger
---

Nobody knows the trouble I've seen  
Nobody knows but Jesus  
Nobody knows the trouble I've seen,  
Glory Hallelujah! 

Sometimes I'm up Sometimes I'm down  
Oh, yes, Lord!  
Sometimes I'm almost to the ground,  
Oh, yes, Lord! 

Nobody knows the trouble I've seen  
Nobody knows but Jesus  
Nobody knows the trouble I've seen,  
Glory Hallelujah! 

Although you see me going' 'long so,  
Oh, yes, Lord  
I have my troubles here below,  
Oh, yes, Lord 

Nobody knows the trouble I've seen  
Nobody knows but Jesus  
Nobody knows the trouble I've seen,  
Glory Hallelujah! 

Now you may think that I don't know,  
Oh, yes, Lord  
But I've had my troubles here below.  
Oh, yes, Lord

Nobody knows the trouble I've seen  
Nobody knows but Jesus  
Nobody knows the trouble I've seen,  
Glory Hallelujah! 

One day when I was walkin' along  
Oh, yes, Lord  
The sky opened up and love came down  
Oh, yes, Lord

Nobody knows the trouble I've seen  
Nobody knows but Jesus  
Nobody knows the trouble I've seen,  
Glory Hallelujah! 

What makes old Satan hate me so?  
Oh, yes, Lord  
He had me once and had to let me go  
Oh, yes, Lord

Nobody knows the trouble I've seen  
Nobody knows but Jesus  
Nobody knows the trouble I've seen,  
Glory Hallelujah! 

I never shall forget that day,  
Oh, yes, Lord  
When Jesus washed my sins away  
Oh, yes, Lord
