---
title: On The Mountain Of The Lord
categories: Engelske sanger
youtube: Cc2xO-hJBMQ
---

They were walking up the mountain  
Isaac asked of Abraham  
"Here I see the wood and fire  
But for the offering, where's the Lamb?" 

Abraham thought for a moment  
The question must have pierced him deep  
But then he gave his son the answer  
Still is true for you and me

"God Himself is here to help us  
There is an offering in store  
All we need will be provided  
On the Mountain of the Lord"

**Chorus :**  
On the Mountain of the Lord  
It will be provided  
On the Mountain of the Lord  
On the Mountain of the Lord  
It will be provided  
On the Mountain of the Lord

They were walking up the mountain  
Two thousand years, the time had come  
The wooden cross, the Lamb of God  
The offering of an only Son

God Himself came down to help us  
Hands were pierced, His blood was poured  
All we need has been provided  
On the Mountain of the Lord

**Chorus :**  
On the Mountain of the Lord  
It will be provided  
On the Mountain of the Lord  
On the Mountain of the Lord  
It will be provided  
On the Mountain of the Lord

You say, ask in Your name  
And we will receive  
Faith can move a mountain  
If we will believe

**Chorus :**  
On the Mountain of the Lord  
It will be provided  
On the Mountain of the Lord  
On the Mountain of the Lord  
It will be provided  
On the Mountain of the Lord
