---
title: Our God
categories: Engelske sanger
youtube: 01Yj7H-eSjM
---

Water You turned into wine  
Opened the eyes of the blind  
There's no one like You  
None like You

Into the darkness You shine  
Out of the ashes we rise  
There's no one like You  
None like You

**Chorus:**  
Our God is greater  
Our God is stronger  
God You are higher than any other  
Our God is healer  
Awesome in power  
Our God, Our God

Into the darkness You shine  
Out of the ashes we rise  
There's no one like You  
None like You

**Chorus:**  
Our God is greater  
Our God is stronger  
God You are higher than any other  
Our God is healer  
Awesome in power  
Our God, Our God
(X2)

(Interlude)

**Bridge:**  
And if our God is for us  
Then who could ever stop us  
And if our God is with us  
Then what could stand against :/ 

**Chorus:**  
Our God is greater  
Our God is stronger  
God You are higher than any other  
Our God is healer  
Awesome in power  
Our God, Our God
(X2)

And if our God is for us  
Then who could ever stop us  
And if our God is with us  
Then what could stand against :/ 
