---
title: Praise The Lord, O my soul
categories: Engelske sanger
youtube: RxjkBQqH7RI
---

**Chorus**  
Praise the Lord, O my soul,  
all my inmost being,  
praise his name  
Praise the Lord, O my soul,  
and forget not all his benefits  
O my soul.

He forgives all of your sin,  
lifts you up out of the pit,  
satisfies you with good things;  
you can fly on eagles wings

**Chorus**  
Praise the Lord, O my soul,  
all my inmost being,  
praise his name  
Praise the Lord, O my soul,  
and forget not all his benefits  
O my soul.

Slow to anger full of love,  
high as heaven up above.  
Far as East is from the West,  
so removed is sin from us

**Chorus**  
Praise the Lord, O my soul,  
all my inmost being,  
praise his name  
Praise the Lord, O my soul,  
and forget not all his benefits  
O my soul.

He knows we are only dust,  
treats us as adopted sons.  
In a short time , we'll be gone,  
but his love will carry on.

**Chorus**  
Praise the Lord, O my soul,  
all my inmost being,  
praise his name  
Praise the Lord, O my soul,  
and forget not all his benefits  
O my soul.

Praise the Lord, He rules us all!  
Praise the Lord in heaven strong.  
Praise the Lord, each angel song,  
all creation sing along.

**Chorus**  
Praise the Lord, O my soul,  
all my inmost being,  
praise his name  
Praise the Lord, O my soul,  
and forget not all his benefits  
O my soul.
