---
title: Prepare the way
categories: Engelske sanger
youtube: uNlUKjlQO-w
---

We've heard the revival stories  
Of ancient and old time glory  
Spirit of God, come do it again  
Miracle-working power  
Moving in signs and wonders  
Spirit of God, come do it again

Prepare the way, He’s coming through  
Ready or not, our God's on the move  
We're gonna see, Heaven on Earth  
Come Holy Spirit, awaken Your church

God, You’re just getting started  
A testimony of more to come  
Spirit of God, come do it in us  
We join in the faith of Heaven  
And prophesy Your kingdom here on Earth  
Spirit of God, come do it in us

Prepare the way, He's coming through  
Ready or not, our God's on the move  
We're gonna see, Heaven on Earth  
Come Holy Spirit, awaken Your church  
Prepare the way, He's coming through  
Ready or not, our God's on the move  
We're gonna see, Heaven on Earth  
Come Holy Spirit, awaken Your church

*Bridge*  
Fire fall, wind come blow  
We're ready for more, ready for more  
Break down the walls, push back the doors  
We’re ready for more, ready for more  
Fire fall, wind come blow  
We’re ready for more, ready for more  
Break down the walls, push back the doors  
We're ready for more, ready for more  
Fire fall, wind come blow  
We’re ready for more, ready for more  
Break down the walls, push back the doors  
We're ready for more, ready for more, oh-oh-oh-oh  
Fire fall, wind come blow  
We're ready for more, ready for more  
Break down the walls, push back the doors  
We're ready for more, ready for more, yeah  
Fire fall, wind come blow  
We’re ready for more, ready for more  
Break down the walls, push back the doors  
We're ready for more, ready for more, yeah  
Fire fall, wind come blow  
We're ready for more, ready for more  
Break down the walls, push back the doors  
We're ready for more

Prepare the way, He's coming through  
Ready or not, our God's on the move  
We're gonna see, Heaven on Earth  
Come Holy Spirit, awaken Your church, yes  

We've heard the revival stories  
Of ancient and old time glory  
Spirit of God, come do it again 