---
title: Psalm 62
categories: Engelske sanger
---

My soul finds rest in God alone, my rock and my salvation  
A fortress strong against my foes and I will not be shaken  
Though lips may bless and hearts may curse  
And lies like arrows pierce me  
I'll fix my heart on righteousness, I'll look to Him who hears
me

O praise Him, Hallelujah, my Delight and my Reward  
Everlasting, never failing, my Redeemer, my God

Find rest, my soul, in God alone amid the world's temptations  
When evil seeks to take a hold I'll cling to my salvation  
Though riches come and riches go, don't set your heart upon them  
The fields of hope in which I sow are harvested in heaven

O praise Him, Hallelujah, my Delight and my Reward  
Everlasting, never failing, my Redeemer, my God

I'll set my gaze on God alone and trust in Him completely  
With every day pour out my soul and He will prove His mercy  
Though life is but a fleeting breath, a sigh too brief to measure  
My King has crushed the curse of death and I am His forever

O praise Him, Hallelujah, my Delight and my Reward  
Everlasting, never failing, my Redeemer, my God  
O praise Him, Hallelujah, my Delight and my Reward  
Everlasting, never failing, my Redeemer, my God

O praise Him, O praise Him, Hallelujah, Hallelujah  
O praise Him, O praise Him, Hallelujah, Hallelujah  
O praise Him, O praise Him, Hallelujah, Hallelujah

O praise Him, Hallelujah, my Delight and my Reward  
Everlasting, never failing, my Redeemer, my God  
O praise Him, Hallelujah, my Delight and my Reward  
Everlasting, never failing, my Redeemer, my God
