---
title: Remember
categories: Engelske sanger
---

Remember when  
he called your name.  
Remember where you started from.  
Remember all you overcame.  
Remember how through him  
you won.

You wanted to know all it was  
To see him, to be him.  
You realized that you were lost  
without him, you found him.  
You saw the way you never could  
repay him, today is the day  
to take time just to...

**Chorus :**  
Remember, remember, Remember  
what you're doing  
this for.  
Remember, remember.  
Remember why he is your Lord.

Remember who you were before.  
Remember where your sorrows led.  
Remember sin had promised more,  
Remember hopelessness instead.

Instead of pleasure filling you,  
it killed you, and still you  
were left with only emptiness  
inside you, to hide you  
would fill your time with other things,  
yet still knew there had to more.  
And then you found him...

**Chorus :**  
Remember, remember, Remember  
what you're doing  
this for.  
Remember, remember.  
Remember why he is your Lord.

Remember seeing what to do,  
Remember eyes were open wide.  
Remember every day was new.  
Remember learning like a child.

A child, you hungered for  
each lesson  
you learned and in turn  
you passed along each morsel to  
another, your brother.  
You tasted that the Lord was good  
--he filled you, now don't you forget  
your first love, got to...

**Chorus :**  
Remember, remember, Remember  
what you're doing  
this for.  
Remember, remember.  
Remember why he is your Lord.

Remember what the future holds.  
Remember dreams you had in youth.  
Remember all the Spirit told.  
Remember promises of fruit.

Fruit that's guaranteed if you stay  
with him, and in him.  
Tomorrow holds the dreams  
that God inspires; still higher  
his power leads,  
from strength to strength  
and victory to victory again.  
And heaven's waiting...

**Chorus :**  
Remember, remember, Remember  
what you're doing  
this for.  
Remember, remember.  
Remember why he is your Lord.
