---
title: Rescue 
categories: Engelske sanger
---

You are the Source of light  
I can't be left behind  
No one else will do  
I will take hold of You

I need You, Jesus, I need You, Jesus...

My heart is Yours for life  
I need Your hand in mine  
No one else will do  
Lord, I put my trust in You

I need You Jesus  
Come to my rescue  
Where else could I go?  
There's no other name by which I am saved  
Oh capture me with grace  
I will follow You

This world has nothing for me  
This world has nothing for me  
This world has nothing for me  
(I will follow You)  
This world has nothing for me

I need You Jesus  
Come to my rescue  
Where else could I go?  
There's no other name by which I am saved  
Capture me with grace  
I will follow You

This world has nothing for me (I will follow you)  
This world has nothing for me (I will follow you)

Oh I need You Jesus  
To come to my rescue  
Where else could I go?  
There's no other name by which I am saved  
Capture me with grace  
Won't You Capture me with grace  
I will follow You  
I will follow You
