---
title: Rescuer
categories: Engelske sanger
youtube: sAg7rn7fH3Q
---

There is good news for the captive  
Good news for the shamed  
There is good news for the one who walked away  
There is good news for the doubter  
The one religion failed  
For the good lord has come to seek and save

He's our rescuer (hey)  
He's our rescuer  
We are free from sin forever more  
Oh how sweet the sound (hey)  
Oh how grace abounds  
We will praise the lord, our rescuer

He is beauty for the blind man  
Riches for the poor  
He is friendship for the one the world ignores  
He is pasture for the weary  
Rest for those who strive  
For the good lord is the way, the truth, the life  
Yes, the good lord is the way, the truth and life

He's our rescuer (hey)  
He's our rescuer  
We are free from sin forever more  
Oh how sweet the sound (hey)  
Oh how grace abounds  
We will praise the lord, our rescuer

So come and be chainless  
Come and be fearless  
Come to the foot of Calvary  
For there is redemption  
For every affliction  
Here at the foot of Calvary

So come and be chainless  
Come and be fearless  
Come to the foot of Calvary  
For there is redemption  
For every affliction  
Here at the foot of Calvary

He's our rescuer (hey)  
He's our rescuer  
We are free from sin forever more  
Oh how sweet the sound (hey)  
Oh how grace abounds  
We will praise the lord, our rescuer