---
title: Shut de do
categories: Engelske sanger
youtube: gmJZrJ2aEYM
---

**Choir:**  
Shut de do, keep out the devil  
Shut de do, keep de devil in the night  
Shut de do, keep out de devil  
Light de candle, everything is alright  
Light de candle, everything is alright

Oh when I was a baby child  
(Shut de do, keep out the devil)  
Good and bad where just a game  
(Shut de do, keep de devil in the night)  
Many years and many trials (Shut de do, keep out the devil)  
they proved to me they're not the same (Shut de do, keep de devil in the
night)

**Choir:**  
Shut de do, keep out the devil  
Shut de do, keep de devil in the night  
Shut de do, keep out de devil  
Light de candle, everything is alright  
Light de candle, everything is alright

Oh, Satan is an evil charmer (Shut de do, keep out the devil)  
He's hungry for a soul to hurt (Shut de do, keep de devil in the night)  
And without your holy armor (Shut de do, keep out the devil)  
He will eat you for dessert (Shut de do, keep de devil in the
night)

**Choir:**  
Shut de do, keep out the devil  
Shut de do, keep de devil in the night  
Shut de do, keep out de devil  
Light de candle, everything is alright  
Light de candle, everything is alright

My mama used to sing this song (Shut de do, keep out the devil)  
Papa used to sing it too (Shut de do, keep de devil in the night)  
Jesus came and called them home (Shut de do, keep out the devil)  
So I sing this song for you (Shut de do, keep de devil in the
night)

**Choir:**  
Shut de do, keep out the devil  
Shut de do, keep de devil in the night  
Shut de do, keep out de devil  
Light de candle, everything is alright  
Light de candle, everything is alright

The Spirit of the Lord is here (Shut de do, keep out the devil)  
Jesus came to set us free (Shut de do, keep de devil in the night)  
And he will overcome our fears (Shut de do, keep out the devil)  
In Him we can have victory (Shut de do, keep de devil in the
night)

**Choir:**  
Shut de do, keep out the devil  
Shut de do, keep de devil in the night  
Shut de do, keep out de devil  
Light de candle, everything is alright  
Light de candle, everything is alright
