---
title: Sing, all nations
categories: Engelske sanger
---

**Chorus:**  
Sing, sing, sing to the Lord all nations  
sing a new song and praise his name  
sing His glory, proclaim salvation  
tell the world that the Lord will reign! :// 

All the Gods of the earth are idols  
only the Lord has a heav ́nly strength  
splendor and majesty are before Him  
for He created the Heavens! 

Sing, sing, sing to the Lord all nations  
sing a new song and praise his name  
sing His glory, proclaim salvation  
tell the world that the Lord will reign! 

Give Him all of your zeal and offerings  
He made you families of His congress  
All He established will stand forever  
so worship Him in His holiness!!

Sing, sing, sing to the Lord all nations  
sing a new song and praise his name  
sing His glory, proclaim salvation  
tell the world that the Lord will reign!

**Bridge:**  
Men: The heavens  
Women: the oceans  
Men: the meadows  
Women: the forests  
All: will sing for joy for He will come!!! 

**Chorus:**  
Sing, sing, sing to the Lord all nations  
sing a new song and praise his name  
sing His glory, proclaim salvation  
tell the world that the Lord will reign! :// 
