---
title: The wonderful cross
categories: Engelske sanger
youtube: oaO3XOI8P6w
---

When I survey the wondrous cross  
on which the Prince of Glory died,  
my richest gain I count but loss  
and pour contempt on all my pride  
See, from His head, His hands, His feet  
sorrow and love flow mingled down  
Did e'er such love and sorrow meet,  
or thorns compose so rich a crown?

**Chorus:**  
Oh, the wonderful cross, oh, the wonderful cross  
bids me come and die and find that I may truly live  
Oh, the wonderful cross, oh, the wonderful cross  
All who gather here by grace draw near and bless  
Your name

Were the whole realm of nature mine  
that were an off'ring far too small  
Love so amazing, so divine  
demands my soul, my life, my all!  
Were the whole realm of nature mine  
that were an off'ring far too small  
Love so amazing, so divine  
demands my soul, my life, my all!

**Chorus:**  
Oh, the wonderful cross, oh, the wonderful cross  
bids me come and die and find that I may truly live  
Oh, the wonderful cross, oh, the wonderful cross  
All who gather here by grace draw near and bless  
Your name

Love so amazing, so divine  
demands my soul, my life, my all!
