---
title: The Greatest Love
categories: Engelske sanger
---

The further one day from the light I walked away  
The longer my shadow was stretching into the dark  
At last my very self disappeared and faded to black  
But even then there was one that saw me!

**Chorus:**  
Never so far, never so gone  
God carries me back home  
Not a second to late He changed my fate  
He's the greatest love I've known

My heart was getting cold by the darkness of  
my sight  
And nothing I did gave meaning to it all  
Then by chance it seemed, a word I did recall  
Put your trust in the light while there still is time!

**Chorus:**  
Never so far, never so gone  
God carries me back home  
Not a second to late He changed my fate  
He's the greatest love I've known

I struggled with pride and was close to giving up  
Shame covered by dark did try holding me back  
I cried out for strength, then I ran into the light  
The mercy and grace I got was without end!

**Chorus:**  
Never so far, never so gone  
God carries me back home  
Not a second to late He changed my fate  
He's the greatest love I've known

And even today I see shades along the way  
Where ever I go they appear from time to time  
Finally I've learned that I'm not as strong as I think  
And what really counts is which way I turn!

**Chorus:**  
Never so far, never so gone  
God carries me back home  
Not a second to late He changed my fate  
He's the greatest love I've known
