---
title: Victory in Jesus
categories: Engelske sanger
---

I heard an old, old story, how a Savior came from glory  
How he gave his life on Calvary to save a wretch like me  
I heard about His groaning, of His precious blood's atoning

**Chorus:**  
Oh victory in Jesus, my Saviour forever  
He sought me and He bought me with his redeeming blood  
He loved me'ere I knew Him and all mo love is due Him  
He plunged me to victory beneath the cleansing flood

I heard about His healing, of His cleansing power revealing  
How He made the lame to walk again and He cause the blind to see  
And then I cried, "Dear Jesus, come and heal my broken spirit"  
I then obeyed His blest command and gained the victory

**Chorus:**  
Oh victory in Jesus, my Saviour forever  
He sought me and He bought me with his redeeming blood  
He loved me'ere I knew Him and all mo love is due Him  
He plunged me to victory beneath the cleansing flood

I head about a mansion He has built for me in glory  
And I heard about the street of gold beyond the crystal sea  
About the angels singing and the old redemption story  
Oh and some sweet day I'll sing up there the song of victory

**Chorus:**  
Oh victory in Jesus, my Saviour forever  
He sought me and He bought me with his redeeming blood  
He loved me'ere I knew Him and all mo love is due Him  
He plunged me to victory beneath the cleansing flood
