---
title: Wade in the water - Eva Cassidy
categories: Engelske sanger
toc: true
format: 
    html: default
    pdf: default
---

Wade in the water  
Wade in the water, children  
Wade in the water  
God's gonna trouble the water

Who's that young girl dressed in red?  
Wade in the water  
Must be the children that Moses led  
And God's gonna trouble the water

Wade in the water  
Wade in the water, children  
Wade in the water  
God's gonna trouble the water

Who's that young girl dressed in white?  
Wade in the water  
Must be the children of the Israelites  
God's gonna trouble the water

Wade in the water  
Wade in the water, children  
Wade in the water  
God's gonna trouble the water

Who's that young girl dressed in blue?  
Wade in the water  
Must be the children that's coming through  
God's gonna trouble the water, yeah

Wade in the water  
Wade in the water, children  
Wade in the water  
And God's gonna trouble the water

You don't believe I've been redeemed  
Wade in the water  
Just see the Holy Ghost looking for me  
God's gonna trouble the water

Wade in the water  
Wade in the water, children  
Wade in the water  
God's gonna trouble the water
