---
title: Wade in the water - Bob Dylan
categories: Engelske sanger
toc: true
format: 
    html: default
    pdf: default
---

Wade in the water  
Wade in the water, children  
Wade in the water  
Gods a-gonna trouble the water  
Gods a-gonna trouble the water.

Well, who are these children all dressed in red?  
Gods a-gonna trouble the water  
Must-a-be the children that moses lead  
Gods a-gonna trouble the water.

Wade in the water  
Wade in the water, children  
Wade in the water  
Gods a-gonna trouble the water  
Gods a-gonna trouble the water.

Well out of the mountain come fire an smoke  
Gods a-gonna trouble the water  
Jehovah nobody be he couldve spoke  
Gods a-gonna trouble the water.

Wade in the water  
Wade in the water, children  
Wade in the water  
Gods a-gonna trouble the water  
Gods a-gonna trouble the water.

Well, I'm walkin down the highway an the waters gettin low  
Gods a-gonna trouble the water.  
Walkin down the highway, nowhere to go  
Gods a-gonna trouble the water.

But it's wade in the water  
Wade in the water, children  
Wade in the water  
Gods a-gonna trouble the water  
Gods a-gonna trouble the water.  
Gods a-gonna trouble the water. 
