---
title: When Israel Was In Egypt's Land
categories: Engelske sanger
youtube: 69TS-rzREXw
---

When Israel was in Egypt's land  
Let my people go  
Oppressed so hard they could not stand  
Let my people go

Go down, Moses, 'way down in Egypt's land  
tell old Pharaoh to let my people go

Thus saith the Lord, bold Moses said  
Let my people go  
If not, I'll smite your first-born dead  
Let my people go

Go down, Moses, 'way down in Egypt's land  
tell old Pharaoh to let my people go

No more shall they in bondage toil  
Let my people go  
Let them come out with Egypt's spoil  
Let my people go

Go down, Moses, 'way down in Egypt's land  
tell old Pharaoh to let my people go

Your foes shall not before you stand  
Let my people go  
And you'll possess fair Canaan's land  
Let my people go

Go down, Moses, 'way down in Egypt's land  
tell old Pharaoh to let my people go

O let us all from bondage flee  
Let my people go  
And let us all in Christ be free  
Let my people go

Go down, Moses, 'way down in Egypt's land  
tell old Pharaoh to let my people go
