---
title: Who am I
categories: Engelske sanger
youtube: uu0lRAl3m4w
---

Who am I,  
that the Lord of all the earth  
Would care to know my name  
Would care to feel my hurt

Who am I,  
that the Bright and Morning Star  
Would choose to light the way  
For my ever wandering heart

**Bridge:**  
Not because of who I am  
But because of what You've done  
Not because of what I've done  
But because of who You're

**Chorus:**  
I am a flower quickly fading  
Here today and gone tomorrow  
A wave tossed in the ocean  
A vapor in the wind  
Still You hear me when I'm calling  
Lord, You catch me when I'm falling  
And You've told me who I am  
I am Yours,  
I am Yours

Who Am I,  
that the eyes that see my sin  
Would look on me with love  
and watch me rise again

Who Am I,  
that the voice that calmed the sea  
Would call out through the rain  
And calm the storm in me

**Bridge:**  
Not because of who I am  
But because of what You've done  
Not because of what I've done  
But because of who You're

**Chorus:**  
I am a flower quickly fading  
Here today and gone tomorrow  
A wave tossed in the ocean  
A vapor in the wind  
Still You hear me when I'm calling  
Lord, You catch me when I'm falling  
And You've told me who I am  
I am Yours,  
I am Yours
