---
title: You are holy
categories: Engelske sanger
youtube: QsYyuK1w3q0
---

You are holy (You are holy)  
You are mighty (You are mighty)  
You are worthy (You are worthy)  
Worthy of praise (Worthy of praise)  
I will follow (I will follow)  
I will listen (I will listen)  
I will love you (I will love you)  
All of my days (All of my days)

**Men:**  
I will sing to  
And worship  
The King who is worthy  
I will love Him, adore Him  
And I will bow down before Him  
And I will sing to and worship  
The King who is worthy  
And I will love Him, adore him  
And I will bow down before Him

**Women:**  
You are Lord of Lords  
You are King of Kings  
You are Mighty God  
Lord of everything

You´re Emmanuel  
You´re the great "I AM"  
You´re my Prince of Peace  
Who is the Lamb

You´re my living God  
You´re my saving grace  
You will reign forever  
You are ancient of days

You are Alpha, Omega, Beginning and End  
You´re my Savior, Messiah, Redeemer and friend

**Both:**  
You´re my Prince of Peace, and I will live my life for you.

