---
title: You are good
categories:
 - Engelske sanger
youtube: eiJ_7zxk0nA
---

Lord, You are good and Your mercy endureth forever  
Lord, You are good and Your mercy endureth forever

**Pre-Chorus**  
People from every nation and tongue  
From generation to generation

We worship You, hallelujah, hallelujah  
We worship You for who You are  
We worship You, hallelujah, hallelujah  
We worship You for who You are  
And You are good

**Interlude**

Lord, You are good and Your mercy endureth forever  
Lord, You are good and Your mercy endureth forever

**Pre-Chorus**  
People from every nation and tongue  
From generation to generation

We worship You, hallelujah, hallelujah  
We worship You for who You are  
We worship You, hallelujah, hallelujah  
We worship You for who You are  
And You are good  
So good, so good, yeah

**Bridge**  
You are good, all the time  
And all the time, You are good, yeah  
You are good, all the time  
All the time, You are good  
You are good, all the time  
All the time, You are good, yeah  
You are good, all the time  
All the time, You are good

**Interlude**  

Lord, You are good and Your mercy endureh forever  
Lord, You are good and Your mercy endureth forever  
Lord, You are good and Your mercy endureth forever  
Lord, You are good and Your mercy endureth forever

**Pre-Chorus**  
People from every nation and tongue  
From generation to generation

**Chorus**  
We worship You, hallelujah, hallelujah  
We worship You for who You are  
We worship You, hallelujah, hallelujah  
We worship You for who You are  
We worship You, hallelujah, hallelujah  
We worship You for who You are  
We worship You, hallelujah, hallelujah  
We worship You for who You are  
For who You are (for who You are)  
Who You are (for who You are)  
And You are good!

**Interlude**  

**Outro**  
You are good, all the time  
And all the time, You are good  
You are good, all the time  
All the time, You are good  
You are good, all the time  
All the time, You are good  
You are good, all the time  
All the time, You are good  
You are good, all the time  
All the time...
