---
title: You are still holy
categories: Engelske sanger
---

Holy, You are still holy  
Even when the darkness surrounds my life  
Sovereign, You are still sovereign  
Even when confusion has blinded my eyes

Lord, I don't deserve Your kind affection  
When my unbelief  
has kept me from Your touch  
I want my life to be a pure reflection  
Of Your love

**Chorus :**  
And so I come into Your chamber  
And I dance at Your feet, Lord  
You are my Saviour  
And I'm at Your mercy  
All that has been in my life  
Up 'til now  
It belongs to You  
You are still holy

Holy, You are still holy  
Even though I don't understand Your ways  
Sovereign, You will be sovereign  
Even when my circumstances don't change

Lord, I don't deserve your tender patience  
When my unbelief has kept me from Your truth  
I want my life to be a sweet devotion  
To You

**Chorus :**  
And so I come into Your chamber  
And I dance at Your feet, Lord  
You are my Saviour  
And I'm at Your mercy  
All that has been in my life  
Up 'til now  
It belongs to You  
You are still holy
