---
title: You are everything
categories: Engelske sanger
---

I'm the one with two left feet  
Standing on a lonely street  
I can't even walk a straight line  
And every time you look at me  
I'm spinning like an autumn leaf  
Bound to hit bottom sometime

**Bridge:**  
Where would I be without someone to save me? Someone who won't let me
fall

**Chorus:**  
You are everything that I live for  
Everything that I can't believe is happening  
You're standing right in front of me  
With arms wide open All I know is  
every day is filled with hope'Cause

You are everything that I breathe for  
And I can't help but breathe You in,  
and breathe again,  
Feeling all this life Within  
Every single beat of my heart

I'm the one with big mistakes  
Big regrets and bigger breaks  
Than I'd ever care to confess  
But You're the one who looks at me  
And sees what I was meant to be  
More than just a beautiful mess

**Bridge:**  
Where would I be without someone to save me? Someone who won't let me
fall

**Chorus:**  
You are everything that I live for  
Everything that I can't believe is happening  
You're standing right in front of me  
With arms wide open All I know is  
every day is filled with hope'Cause

You're everything good in my life  
Everything honest and true  
And all of those stars hangin' up in the sky  
Could never shine brighter than You

**Chorus:**  
You are everything that I live for  
Everything that I can't believe is happening  
You're standing right in front of me  
With arms wide open All I know is  
every day is filled with hope'Cause
