---
title: "You Make Me"
categories: "Engelske sanger"
---

Every drop of rain reminds me of the love You give from above  
Every beam of sunlight takes me in to Your embrace,  
a place where I feel warm and safe

**Chorus 1**  
All Your giving makes my hands  
achie' achie' achie' achieving :/ 

Every step I make reminds me of the Counsellor in my heart  
Every breath I'm taking shows me I have no control  
for You will have the final call

**Chorus 2**    
All Your loving Makes my feet  
a'go a'go a'go a'going :/ 

Every day I live reminds me of the blood You gave on the cross  
Every friend You're giving adds to the angels helping me  
until the end I'm seeing Thee

**Chorus 3**  
All Your caring Makes my mouth  
a'share' a'share' a'share' a'sharing :/ 

**Chorus 4**  
All Your giving makes my hands  
achie' achie' achie' achieving

All Your loving Makes my feet  
a'go a'go a'go a'going

All Your caring Makes my mouth  
a'share' a'share' a'share' a'sharing

All Your loving Makes my feet  
a'go a'go a'go a'going
