project:
  type: website

website:
  title: "Sangboka"
  bread-crumbs: true  
  page-navigation: true
  back-to-top-navigation: true

  page-footer:
    left: "Website copyright by its creator"
    center: "Website created with Quarto"
    right: "Songs copyright their respective authors"
  navbar: 
    background: primary
    search: true

    right:
      - href: https://kristiforsamling.net
        text: Kristiforsamling.net
        aria-label: Kristiforsamling.net
  sidebar:
    style: "floating"
    search: false
    contents: auto

format:
  html:
    theme: flatly
